steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/virtual-sylph-105892-k2/bitimsiz-app-repo/bitimsiz-app-backend:$COMMIT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/virtual-sylph-105892-k2/bitimsiz-app-repo/bitimsiz-app-backend:$COMMIT_SHA']
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'europe-west1-docker.pkg.dev/virtual-sylph-105892-k2/bitimsiz-app-repo/bitimsiz-app-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'bitimsiz-app-connector'
      - '--vpc-egress'
      - 'all-traffic'
      - '--set-secrets=NODE_ENV=projects/1097302283998/secrets/NODE_ENV:latest'
      - '--set-secrets=REDIS_URL=projects/1097302283998/secrets/REDIS_URL:latest'
      - '--set-secrets=JWT_SECRET=projects/1097302283998/secrets/JWT_SECRET:latest'
      - '--set-secrets=JWT_REFRESH_SECRET=projects/1097302283998/secrets/JWT_REFRESH_SECRET:latest'
      - '--set-secrets=FIREBASE_SERVICE_ACCOUNT_BASE64=projects/1097302283998/secrets/FIREBASE_SERVICE_ACCOUNT_BASE64:latest'
      - '--set-secrets=PHONE_ENCRYPTION_KEY=projects/1097302283998/secrets/PHONE_ENCRYPTION_KEY:latest'
      - '--set-secrets=MONGODB_URI=projects/1097302283998/secrets/MONGODB_URI:latest'
      - '--set-secrets=CORS_ORIGIN=projects/1097302283998/secrets/CORS_ORIGIN:latest'
      - '--set-secrets=GCS_BUCKET_NAME=projects/1097302283998/secrets/GCS_BUCKET_NAME:latest'